### ISSUE TITLE
What should this driver do?

### ISSUE THREAD

**Issue by GabMus** [sammko/hid-glorious#1]
I have a glorious model o mouse. I use it exclusively under Linux and all of the buttons as well as the RGB lighting work out of the box. Am I missing something?

**Comment by sammko** [comment]
Sorry for not writing any description in this repository, it was just for the time being. The driver fixes "Consumer Control" events, which are dropped by the Linux kernel, due to a bug in the report descriptor of the mouse. These include multimedia actions and all the "extra keys" you would find on a keyboard, for example on the Fn keys. (Play/Pause, next/previous, volume control and such.) I am used to having a Play/Pause button on my mouse, which does not currently work on Linux.

The driver has recently been merged to mainline Linux, see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77a36a3ab4ff17fad23831192e3694a3c5a1750d . It will be available in 5.7 when it comes out in a few months.
Also feel free to learn more in this discussion. https://lore.kernel.org/lkml/CAHk-=wgy8AM+BOt4jhnoQ+wa=YVyXT4ARg=qEYC=S-OW4ZjZzw@mail.gmail.com/T/#u

If you use arch linux, a PKGBUILD is available in the AUR for the time being. https://aur.archlinux.org/packages/hid-glorious-dkms/

Of course, if you don't use any of the consumer control keys, you do not need this driver.
